### ISSUE TITLE
Error in cv2.findChessboardCorners

### ISSUE THREAD

**Issue by carlos-andrade8** [smidm/video2calibration#1]
Hi,

I'm getting the following error when I run the script:

File "./calibrate.py", line 54, in <module>
    found, corners = cv2.findChessboardCorners(img, pattern_size, cv2.CALIB_CB_FILTER_QUADS)
TypeError: corners is not a numpy array, neither a scalar

any ideas?

Thanks

**Comment by smidm** [comment]
Quick search shows a hint here https://stackoverflow.com/a/35276031/322468. The function parameters changed. Try:

` found, corners = cv2.findChessboardCorners(img, pattern_size, flags=cv2.CALIB_CB_FILTER_QUADS)`

Does it work?

**Comment by MI-Hussain** [comment]
> Quick search shows a hint here https://stackoverflow.com/a/35276031/322468. The function parameters changed. Try:
> 
> ` found, corners = cv2.findChessboardCorners(img, pattern_size, flags=cv2.CALIB_CB_FILTER_QUADS)`
> 
> Does it work?

yes its working thanks

**Comment by smidm** [comment]
fixed in https://github.com/smidm/video2calibration/commit/9593bb276fca4b67d5a92bfc9c9a08b84624260f
