### ISSUE TITLE
Calibration pattern size unclear

### ISSUE THREAD

**Issue by petergerten** [smidm/video2calibration#3]
The png image mentions a size of 9*6 but the aspect ratio of the png is different. Now it comes down on how the printer driver/printer handles this. Could you clarify what the *exact* size of the pattern is? (or the individual 'fields' to verify after printing)

**Comment by smidm** [comment]
The 9 x 6 is referring to the contact points of black and white squares that are used for calibration, see the debug visualization.

The pattern should be printed without any scaling such that the squares are really squares. I've updated the README to clarify this.

![detected corner points](https://raw.githubusercontent.com/smidm/video2calibration/master/example_output/debug/0280.png)
